sudo: required
dist: xenial
language: python
addons:
  firefox: "70.0.1"
services:
  - xvfb
before_script:
  - pip install -r requirements.txt
  - pip install vtk pixelmatch flask msgpack webdriver_manager selenium
  - cd k3d
script: pytest
